import type { LibraryResourceContent } from './types'

// Real, publicly available documents. Every fileUrl was checked against the
// publisher's official site (October 2026). library.wmo.int pages sit behind a
// browser "slide to continue" check, so those URLs were confirmed through the
// official wmo.int / community.wmo.int pages that link to them.
export const libraryResources: LibraryResourceContent[] = [
  {
    slug: 'wmo-8-guide-instruments-methods-observation',
    title: 'Guide to Instruments and Methods of Observation (WMO-No. 8), 2024 edition',
    description:
      'Jahon meteorologiya tashkiloti (JMT)ning asbob va kuzatuv usullari bo‘yicha asosiy qo‘llanmasi (CIMO Guide): harorat, namlik, bosim, shamol, yog‘in, radiatsiya va boshqa o‘zgaruvchilarni o‘lchash, asboblarni joylashtirish, kalibrlash va o‘lchash noaniqligini baholashni yoritadi. Meteorologik stansiya xodimlari kuzatuv maydonchasini tashkil etish, asbob tanlash va o‘lchash sifatini nazorat qilishda undan tayanch manba sifatida foydalanadi.',
    type: 'manual',
    category: 'Meteorologik kuzatuvlar',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2024,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/41650-guide-to-instruments-and-methods-of-observation',
    fileType: 'html',
    tags: ['wmo', 'kuzatuvlar', 'asboblar', 'kalibrlash', 'cimo'],
  },
  {
    slug: 'wmo-49-technical-regulations-vol-1',
    title: 'Technical Regulations, Volume I: General Meteorological Standards and Recommended Practices (WMO-No. 49)',
    description:
      'JMT Texnik reglamentining I jildi meteorologiya va operativ gidrologiya sohasidagi umumiy standartlar va tavsiya etilgan amaliyotlarni belgilaydi (2023-yil nashri, 2025-yilda yangilangan). Milliy gidrometeorologiya xizmati kuzatuv, ma’lumot almashinuvi va xizmat ko‘rsatishdagi xalqaro majburiyatlarini aniqlash hamda ichki tartiblarni JMT talablariga moslashtirishda undan foydalanadi.',
    type: 'normative',
    category: 'Me’yoriy hujjatlar',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2025,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/35722-technical-regulations-volume-i-general-meteorological-standards-and-recommended-practices',
    fileType: 'html',
    tags: ['wmo', 'texnik-reglament', 'standartlar', 'normativ'],
  },
  {
    slug: 'wmo-306-manual-on-codes-vol-1-1',
    title: 'Manual on Codes – International Codes, Volume I.1: Part A – Alphanumeric Codes (WMO-No. 306)',
    description:
      'JMT Texnik reglamentining II ilovasi bo‘lgan Kodlar bo‘yicha qo‘llanma: SYNOP, TEMP, METAR, TAF, CLIMAT kabi xalqaro alfavit-raqamli kod shakllari va ularni tuzish qoidalarini o‘z ichiga oladi. Kuzatuvchilar va sinoptiklar telegrammalarni to‘g‘ri kodlash, dekodlash va ulardagi xatolarni aniqlashda ushbu hujjatga tayanadi.',
    type: 'manual',
    category: 'Sinoptik meteorologiya',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2019,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/35713-manual-on-codes-international-codes-volume-i-1',
    fileType: 'html',
    tags: ['wmo', 'kodlar', 'synop', 'metar', 'sinoptika'],
  },
  {
    slug: 'wmo-485-manual-wipps',
    title: 'Manual on the WMO Integrated Processing and Prediction System (WIPPS) (WMO-No. 485)',
    description:
      'Ilgari Global ma’lumotlarni qayta ishlash va prognozlash tizimi (GDPFS) bo‘yicha qo‘llanma deb nomlangan JMT Texnik reglamentining IV ilovasi. Unda global va mintaqaviy markazlarning vazifalari, raqamli prognoz mahsulotlari va prognozlarni verifikatsiya qilish talablari belgilangan; sinoptiklar markazlar mahsulotlaridan foydalanish tartibini shu hujjat asosida o‘rganadi.',
    type: 'manual',
    category: 'Sinoptik meteorologiya',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2024,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/35703-manual-on-the-wmo-integrated-processing-and-prediction-system',
    fileType: 'html',
    tags: ['wmo', 'wipps', 'gdpfs', 'prognoz', 'raqamli-prognoz'],
  },
  {
    slug: 'wmo-1160-manual-wigos',
    title: 'Manual on the WMO Integrated Global Observing System (WIGOS) (WMO-No. 1160)',
    description:
      'JMT Integratsiyalashgan global kuzatuv tizimi (WIGOS) bo‘yicha qo‘llanma, Texnik reglamentning VIII ilovasi: yer usti, aerologik, gidrologik va kosmik kuzatuvlarni tashkil etish, WIGOS stansiya identifikatorlari va metama’lumotlarga qo‘yiladigan talablarni belgilaydi. Kuzatuv tarmog‘ini rejalashtirish va stansiya metama’lumotlarini yuritishda qo‘llaniladi.',
    type: 'manual',
    category: 'Meteorologik kuzatuvlar',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2023,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/55063-manual-on-the-wmo-integrated-global-observing-system',
    fileType: 'html',
    tags: ['wmo', 'wigos', 'kuzatuv-tarmogi', 'metamalumot'],
  },
  {
    slug: 'wmo-100-guide-climatological-practices',
    title: 'Guide to Climatological Practices (WMO-No. 100), 2023 edition',
    description:
      'JMT Iqlimshunoslik amaliyoti bo‘yicha qo‘llanmasining to‘rtinchi nashri iqlim kuzatuvlari, ma’lumotlarni boshqarish, statistik tahlil, iqlim monitoringi va iqlim xizmatlarini ko‘rsatishning zamonaviy amaliyotini bayon qiladi. Iqlim bo‘limi xodimlari iqlim ma’lumotnomalari, sharhlar va iqlim xizmatlari mahsulotlarini tayyorlashda undan foydalanadi.',
    type: 'manual',
    category: 'Iqlimshunoslik',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2023,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/60113-guide-to-climatological-practices',
    fileType: 'html',
    tags: ['wmo', 'iqlimshunoslik', 'iqlim-xizmatlari', 'statistika'],
  },
  {
    slug: 'wmo-1203-climate-normals-guidelines',
    title: 'WMO Guidelines on the Calculation of Climate Normals (WMO-No. 1203)',
    description:
      'JMTning iqlim me’yorlarini hisoblash bo‘yicha yo‘riqnomasi: 1991–2020 standart davri, ma’lumotlar to‘liqligi mezonlari, yetishmayotgan qiymatlar bilan ishlash va turli meteorologik elementlar uchun me’yorlarni hisoblash usullarini belgilaydi. Iqlimshunoslar stansiyalar bo‘yicha ko‘p yillik o‘rtacha qiymatlarni yangilash va anomaliyalarni hisoblashda shu tartibga amal qiladi.',
    type: 'manual',
    category: 'Iqlimshunoslik',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2017,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/55797-wmo-guidelines-on-the-calculation-of-climate-normals',
    fileType: 'html',
    tags: ['wmo', 'iqlim-meyorlari', '1991-2020', 'anomaliya'],
  },
  {
    slug: 'wmo-1269-surface-station-data-qc-qa',
    title: 'Guidelines on Surface Station Data Quality Control and Quality Assurance for Climate Applications (WMO-No. 1269)',
    description:
      'Iqlim maqsadlari uchun yer usti stansiyalari ma’lumotlari sifatini nazorat qilish (QC) va ta’minlash (QA) bo‘yicha JMT yo‘riqnomasi: diapazon, ichki moslik, vaqt va fazoviy izchillik tekshiruvlari hamda sifat bayroqlarini qo‘llashni tavsiflaydi. Ma’lumotlar bazasini yurituvchi mutaxassislar avtomatik va ekspert tekshiruv tartiblarini joriy etishda undan foydalanadi.',
    type: 'manual',
    category: 'Ma’lumotlar sifati',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2021,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/57727-guidelines-on-surface-station-data-quality-control-and-quality-assurance-for-climate-applications',
    fileType: 'html',
    tags: ['wmo', 'sifat-nazorati', 'qc', 'qa', 'iqlim-malumotlari'],
  },
  {
    slug: 'wmo-168-guide-hydrological-practices-vol-1',
    title: 'Guide to Hydrological Practices, Volume I: Hydrology – From Measurement to Hydrological Information (WMO-No. 168)',
    description:
      'Gidrologiya amaliyoti bo‘yicha qo‘llanmaning I jildi (6-nashr): yog‘in, bug‘lanish, suv sathi va sarfi, oqiziqlar, yer osti suvlari va suv sifatini o‘lchash, gidrometrik tarmoqni loyihalash hamda ma’lumotlarni qayta ishlash va saqlashni qamrab oladi. Gidrologik postlar va kuzatuv tarmog‘i xodimlari uchun asosiy metodik manba hisoblanadi.',
    type: 'manual',
    category: 'Gidrologiya',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2008,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/35804-guide-to-hydrological-practices-volume-i',
    fileType: 'html',
    tags: ['wmo', 'gidrologiya', 'gidrometriya', 'suv-sarfi', 'kuzatuv-tarmogi'],
  },
  {
    slug: 'wmo-1044-manual-stream-gauging-vol-1',
    title: 'Manual on Stream Gauging, Volume I: Fieldwork (WMO-No. 1044)',
    description:
      'Daryo oqimini o‘lchash bo‘yicha qo‘llanmaning I jildi: gidrometrik stvor joyini tanlash, suv sathini o‘lchash, oqim tezligini aniqlash va suv sarfini o‘lchash usullarini bosqichma-bosqich bayon qiladi. Asosan gidrologik texniklar va dala o‘lchovlarini bajaruvchi xodimlar uchun mo‘ljallangan.',
    type: 'manual',
    category: 'Gidrologiya',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2010,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/36041-manual-on-stream-gauging-vol-i-fieldwork',
    fileType: 'html',
    tags: ['wmo', 'gidrometriya', 'suv-sarfi', 'dala-ishlari'],
  },
  {
    slug: 'wmo-1044-manual-stream-gauging-vol-2',
    title: 'Manual on Stream Gauging, Volume II: Computation of Discharge (WMO-No. 1044)',
    description:
      'Daryo oqimini o‘lchash bo‘yicha qo‘llanmaning II jildi suv sathi va sarfi o‘rtasidagi bog‘lanish egri chizig‘ini qurish, uni tekshirish va o‘zgaruvchan o‘zan sharoitida suv sarfini hisoblash usullariga bag‘ishlangan. Gidrologlar kuzatuv qatorlaridan kunlik suv sarflarini hisoblash va natijalar sifatini baholashda foydalanadi.',
    type: 'manual',
    category: 'Gidrologiya',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2010,
    language: 'en',
    fileUrl: 'https://library.wmo.int/records/item/35841-manual-on-stream-gauging-vol-ii-computation-of-discharge',
    fileType: 'html',
    tags: ['wmo', 'suv-sarfi', 'sarf-egri-chizigi', 'gidrologiya'],
  },
  {
    slug: 'wmo-1150-impact-based-forecast-warning',
    title: 'WMO Guidelines on Multi-hazard Impact-based Forecast and Warning Services (WMO-No. 1150)',
    description:
      'JMTning ta’sirga asoslangan ko‘p xavfli prognoz va ogohlantirish xizmatlari (IBFWS) bo‘yicha yo‘riqnomasi: ob-havo qanday bo‘lishini emas, balki u qanday oqibatlarga olib kelishini ko‘rsatuvchi ogohlantirishlarga o‘tish bosqichlari va hamkorlik mexanizmlarini tushuntiradi. Sinoptiklar xavfli hodisalar bo‘yicha ogohlantirish mezonlarini ta’sir va zaiflik ma’lumotlari bilan bog‘lashda foydalanadi.',
    type: 'manual',
    category: 'Xavfli hodisalar',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2015,
    language: 'en',
    pages: 34,
    fileUrl: 'https://etrp.wmo.int/pluginfile.php/16270/mod_resource/content/0/wmo_1150_en.pdf',
    fileType: 'pdf',
    tags: ['wmo', 'ogohlantirish', 'xavfli-hodisalar', 'ibfws'],
  },
  {
    slug: 'wmo-134-guide-agrometeorological-practices',
    title: 'Guide to Agricultural Meteorological Practices (GAMP), 2010 Edition (WMO-No. 134)',
    description:
      'Agrometeorologiya amaliyoti bo‘yicha JMT qo‘llanmasi (2010-yil nashri, 2012-yilda yangilangan): agrometeorologik kuzatuvlar, ma’lumotlarni statistik tahlil qilish, agrometeorologik prognozlar, iqlim va ob-havo xavflarini baholash hamda asosiy ekinlarga qo‘llanilishini yoritadi. Agrometeorologlar dala kuzatuvlari va qishloq xo‘jaligi uchun maslahat byulletenlarini tayyorlashda foydalanadi.',
    type: 'manual',
    category: 'Agrometeorologiya',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2010,
    language: 'en',
    fileUrl: 'https://community.wmo.int/site/knowledge-hub/programmes-and-initiatives/agricultural-meteorology/guide-agricultural-meteorological-practices-gamp2010-edition-wmo-no134',
    fileType: 'html',
    tags: ['wmo', 'agrometeorologiya', 'ekinlar', 'qurgoqchilik'],
  },
  {
    slug: 'wmo-state-of-global-climate-2025',
    title: 'State of the Global Climate 2025',
    description:
      'JMTning 2025-yil uchun global iqlim holati to‘g‘risidagi yillik ma’ruzasi (2026-yil 23-martda e’lon qilingan): harorat, issiqxona gazlari, okean issiqligi, dengiz sathi, muzliklar va dengiz muzlari ko‘rsatkichlari hamda ekstremal hodisalar oqibatlarini umumlashtiradi. Iqlim bo‘limi mutaxassislari milliy iqlim sharhlarini global kontekst bilan solishtirishda foydalanadi.',
    type: 'document',
    category: 'Iqlim o‘zgarishi',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2026,
    language: 'en',
    fileUrl: 'https://library.wmo.int/idurl/4/69807',
    fileType: 'html',
    tags: ['wmo', 'iqlim-ozgarishi', 'global-harorat', 'yillik-maruza'],
  },
  {
    slug: 'wmo-state-of-climate-asia-2025',
    title: 'State of the Climate in Asia 2025',
    description:
      'JMTning Osiyo mintaqasi bo‘yicha 2025-yil iqlim holati ma’ruzasi (2026-yil iyunida e’lon qilingan): mintaqaviy harorat anomaliyalari, yog‘inlar, Baland tog‘li Osiyo muzliklarining massa yo‘qotishi va ekstremal hodisalar oqibatlarini tahlil qiladi. O‘zbekiston uchun muhim bo‘lgan muzliklar va suv resurslari tendensiyalarini mintaqaviy miqyosda baholashda foydalaniladi.',
    type: 'document',
    category: 'Iqlim o‘zgarishi',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2026,
    language: 'en',
    fileUrl: 'https://library.wmo.int/idurl/4/69873',
    fileType: 'html',
    tags: ['wmo', 'osiyo', 'muzliklar', 'iqlim-ozgarishi'],
  },
  {
    slug: 'wmo-407-international-cloud-atlas',
    title: 'Международный атлас облаков. Наставление по наблюдению за облаками и другими метеорами (ВМО-№ 407)',
    description:
      'JMT Xalqaro bulutlar atlasining 2017-yildagi onlayn nashri (rus tilida): bulut turlari, tur xillari va navlarining fotosuratli tavsiflari hamda gidrometeorlar, litometeorlar, fotometeorlar va elektrometeorlar tasnifini beradi. Kuzatuvchilar bulutlilikni yagona mezonda aniqlash va kodlashda undan foydalanadi.',
    type: 'manual',
    category: 'Meteorologik kuzatuvlar',
    author: 'Всемирная метеорологическая организация (ВМО)',
    publisher: 'Всемирная метеорологическая организация',
    year: 2017,
    language: 'ru',
    fileUrl: 'https://cloudatlas.wmo.int/ru/home.html',
    fileType: 'html',
    tags: ['wmo', 'bulutlar', 'atlas', 'kuzatuvlar'],
  },
  {
    slug: 'wmo-1257-weather-radar-data-processing',
    title: 'Guide to Operational Weather Radar Best Practices, Volume VI: Weather Radar Data Processing (WMO-No. 1257)',
    description:
      'JMTning operativ meteorologik radarlar bo‘yicha eng yaxshi amaliyotlar qo‘llanmasining VI jildi radar ma’lumotlarini qayta ishlashga bag‘ishlangan: xom signaldan sifat nazoratidan o‘tgan mahsulotlargacha bo‘lgan bosqichlar va xatolik manbalarini tuzatish usullarini yoritadi. Radar meteorologlari va sinoptiklar radar mahsulotlarining ishonchliligini baholashda foydalanadi.',
    type: 'manual',
    category: 'Masofadan zondlash',
    author: 'World Meteorological Organization (WMO)',
    publisher: 'World Meteorological Organization',
    year: 2024,
    language: 'en',
    fileUrl: 'https://library.wmo.int/idurl/4/69563',
    fileType: 'html',
    tags: ['wmo', 'radar', 'masofadan-zondlash', 'sifat-nazorati'],
  },
  {
    slug: 'ipcc-ar6-synthesis-report-spm',
    title: 'Climate Change 2023: Synthesis Report. Summary for Policymakers',
    description:
      'IPCC Oltinchi baholash ma’ruzasi (AR6) Sintez ma’ruzasining siyosatchilar uchun qisqacha xulosasi: kuzatilgan isish va uning sabablari, kelajakdagi xavflar hamda moslashuv va yumshatish choralari bo‘yicha asosiy ilmiy xulosalarni jamlaydi. Iqlim o‘zgarishi bo‘yicha ma’lumotnomalar, taqdimotlar va o‘quv mashg‘ulotlarida ishonchli manba sifatida foydalaniladi.',
    type: 'document',
    category: 'Iqlim o‘zgarishi',
    author: 'IPCC (Core Writing Team, H. Lee and J. Romero, eds.)',
    publisher: 'Intergovernmental Panel on Climate Change (IPCC)',
    year: 2023,
    language: 'en',
    pages: 42,
    fileUrl: 'https://www.ipcc.ch/report/ar6/syr/downloads/report/IPCC_AR6_SYR_SPM.pdf',
    fileType: 'pdf',
    tags: ['ipcc', 'ar6', 'iqlim-ozgarishi', 'moslashuv'],
  },
  {
    slug: 'who-global-air-quality-guidelines-2021',
    title: 'WHO global air quality guidelines: particulate matter (PM2.5 and PM10), ozone, nitrogen dioxide, sulfur dioxide and carbon monoxide',
    description:
      'Jahon sog‘liqni saqlash tashkilotining 2021-yildagi global havo sifati tavsiyalari: PM2.5, PM10, ozon, azot dioksidi, oltingugurt dioksidi va uglerod oksidi uchun tavsiya etilgan darajalar hamda oraliq maqsadlarni belgilaydi. Atmosfera havosi monitoringi mutaxassislari o‘lchov natijalarini sog‘liq uchun xavf mezonlari bilan solishtirishda foydalanadi.',
    type: 'manual',
    category: 'Atmosfera havosi sifati',
    author: 'World Health Organization (WHO)',
    publisher: 'World Health Organization',
    year: 2021,
    language: 'en',
    pages: 290,
    fileUrl: 'https://www.who.int/publications/i/item/9789240034228',
    fileType: 'html',
    tags: ['who', 'havo-sifati', 'pm2.5', 'ifloslanish'],
  },
  {
    slug: 'ilo-osh-2001-guidelines',
    title: 'Руководство по системам управления охраной труда. МОТ–СУОТ 2001 (ILO-OSH 2001)',
    description:
      'Xalqaro mehnat tashkilotining mehnatni muhofaza qilishni boshqarish tizimlari bo‘yicha qo‘llanmasi (ILO-OSH 2001) rus tilidagi nashri: siyosat, tashkil etish, rejalashtirish, natijalarni baholash va takomillashtirish elementlarini bayon qiladi. Tashkilotda xavflarni boshqarish va mehnat muhofazasi tizimini yo‘lga qo‘yishda namunaviy model sifatida qo‘llaniladi.',
    type: 'manual',
    category: 'Mehnat muhofazasi',
    author: 'Международная организация труда (МОТ)',
    publisher: 'Международное бюро труда, Женева',
    year: 2003,
    language: 'ru',
    pages: 32,
    fileUrl: 'https://www.ilo.org/sites/default/files/wcmsp5/groups/public/@ed_protect/@protrav/@safework/documents/normativeinstrument/wcms_125017.pdf',
    fileType: 'pdf',
    tags: ['ilo', 'mehnat-muhofazasi', 'boshqaruv-tizimi', 'xavfsizlik'],
  },
  {
    slug: 'fao-56-crop-evapotranspiration',
    title: 'Crop evapotranspiration – Guidelines for computing crop water requirements (FAO Irrigation and Drainage Paper 56)',
    description:
      'FAOning sug‘orish va drenaj bo‘yicha 56-sonli nashri: Penman–Monteith usulida etalon evapotranspiratsiyani (ET0) hisoblash, ekin koeffitsientlari (Kc) va ekinlarning suvga bo‘lgan ehtiyojini aniqlash bo‘yicha xalqaro standart metodika. Agrometeorologlar meteorologik ma’lumotlar asosida sug‘orish rejimi va suv iste’moli hisob-kitoblarini bajarishda foydalanadi.',
    type: 'book',
    category: 'Agrometeorologiya',
    author: 'R. G. Allen, L. S. Pereira, D. Raes, M. Smith',
    publisher: 'Food and Agriculture Organization of the United Nations (FAO)',
    year: 1998,
    language: 'en',
    pages: 300,
    fileUrl: 'https://www.fao.org/4/x0490e/x0490e00.htm',
    fileType: 'html',
    tags: ['fao', 'evapotranspiratsiya', 'sugorish', 'agrometeorologiya'],
  },
  {
    slug: 'sendai-framework-drr-2015-2030',
    title: 'Сендайская рамочная программа по снижению риска бедствий на 2015–2030 гг.',
    description:
      '2015–2030-yillarga mo‘ljallangan Sendai ofatlar xavfini kamaytirish bo‘yicha asos dasturining rus tilidagi rasmiy matni: yetti global maqsad va to‘rt ustuvor yo‘nalishni, jumladan, xavfni tushunish va erta ogohlantirishni kuchaytirishni belgilaydi. Gidrometeorologiya xizmatining erta ogohlantirish va favqulodda vaziyatlarga tayyorgarlik faoliyatini xalqaro majburiyatlar bilan bog‘lashda foydalaniladi.',
    type: 'document',
    category: 'Xavfli hodisalar',
    author: 'Организация Объединённых Наций',
    publisher: 'Управление ООН по снижению риска бедствий (УСРБ ООН)',
    year: 2015,
    language: 'ru',
    pages: 40,
    fileUrl: 'https://www.undrr.org/media/16178/download',
    fileType: 'pdf',
    tags: ['undrr', 'sendai', 'ofat-xavfi', 'erta-ogohlantirish'],
  },
  {
    slug: 'uz-law-hydrometeorological-activity-zru-745',
    title: 'Закон Республики Узбекистан «О гидрометеорологической деятельности» (№ ЗРУ-745 от 12.01.2022)',
    description:
      'O‘zbekiston Respublikasining 2022-yil 12-yanvardagi O‘RQ-745-son «Gidrometeorologiya faoliyati to‘g‘risida»gi Qonuni (rus tilidagi matni): faoliyatning asosiy prinsiplari, ob’ektlari va sub’ektlari, davlat organlarining vakolatlari hamda gidrometeorologik axborot ishlab chiqaruvchi va iste’molchilarining huquq va majburiyatlarini belgilaydi. Soha xodimlari o‘z faoliyatining huquqiy asosini bilish uchun o‘rganadi.',
    type: 'normative',
    category: 'Me’yoriy hujjatlar',
    author: 'Республика Узбекистан',
    publisher: 'Национальная база данных законодательства Республики Узбекистан (lex.uz)',
    year: 2022,
    language: 'ru',
    fileUrl: 'https://lex.uz/ru/docs/5819321',
    fileType: 'html',
    tags: ['qonun', 'gidrometeorologiya', 'lex.uz', 'normativ'],
  },
  {
    slug: 'uz-law-atmospheric-air-protection-353-i',
    title: 'Закон Республики Узбекистан «Об охране атмосферного воздуха» (№ 353-I от 27.12.1996)',
    description:
      'O‘zbekiston Respublikasining 1996-yil 27-dekabrdagi 353-I-son «Atmosfera havosini muhofaza qilish to‘g‘risida»gi Qonuni (amaldagi tahriri, rus tilida): atmosfera havosi sifati normativlari, statsionar va harakatlanuvchi manbalardan chiqariladigan zararli moddalarni tartibga solish hamda davlat organlari vakolatlarini belgilaydi. Havo sifati kuzatuvlari bilan shug‘ullanuvchi mutaxassislar faoliyatining huquqiy asosi hisoblanadi.',
    type: 'normative',
    category: 'Atmosfera havosi sifati',
    author: 'Республика Узбекистан',
    publisher: 'Национальная база данных законодательства Республики Узбекистан (lex.uz)',
    year: 1996,
    language: 'ru',
    fileUrl: 'https://lex.uz/ru/docs/58400',
    fileType: 'html',
    tags: ['qonun', 'havo-sifati', 'lex.uz', 'normativ'],
  },
  {
    slug: 'uz-labour-code-2022',
    title: 'Трудовой кодекс Республики Узбекистан (утверждён Законом № ЗРУ-798 от 28.10.2022)',
    description:
      'O‘zbekiston Respublikasining 2022-yil 28-oktabrdagi O‘RQ-798-son Qonuni bilan tasdiqlangan va 2023-yil 30-apreldan kuchga kirgan Mehnat kodeksi (rus tilida). Kodeksning 20-bobi mehnatni muhofaza qilish talablari, ish beruvchi va xodimning huquq hamda majburiyatlari, yo‘l-yo‘riq berish, tibbiy ko‘riklar va ishlab chiqarishdagi baxtsiz hodisalarni tekshirish tartibini belgilaydi.',
    type: 'normative',
    category: 'Mehnat muhofazasi',
    author: 'Республика Узбекистан',
    publisher: 'Национальная база данных законодательства Республики Узбекистан (lex.uz)',
    year: 2022,
    language: 'ru',
    fileUrl: 'https://lex.uz/ru/docs/6257291',
    fileType: 'html',
    tags: ['mehnat-kodeksi', 'mehnat-muhofazasi', 'lex.uz', 'normativ'],
  },
]
